theme: jekyll-theme-hacker

title: CG's Portfolio

description: "ninjakira.github.io"
  [![Linkedin Badge](https://img.shields.io/badge/-sihcheeguan-blue?style=flat&logo=Linkedin&logoColor=white)](https://www.linkedin.com/in/sihcheeguan/)
  [![Website Badge](https://img.shields.io/badge/-ninjakira.github.io-47CCCC?style=flat&logo=Google-Chrome&logoColor=white)](https://ninjakira.github.io)

